# Arduino libraries packaged as ESP-IDF 4.4 components.
#
# Each attribute in `components` is a derivation whose $out IS an IDF
# component directory: a generated CMakeLists.txt (IDF 4.4 style
# idf_component_register) plus the library sources copied from the pinned
# flake input. Point EXTRA_COMPONENT_DIRS at a directory containing all of
# these (e.g. a linkFarm over `components`).
#
# srcs :: attrset, keys = flake input names (kebab-case), values = store
# paths of the pinned library sources (flake inputs with flake = false).
{ pkgs, srcs }:

let
  inherit (pkgs) lib;

  quoted = xs: lib.concatMapStringsSep " " (x: ''"${x}"'') xs;

  # Assemble one IDF component dir:
  #  - full library source tree copied in (IDF only compiles listed SRCS,
  #    so examples/ etc. are inert),
  #  - our CMakeLists.txt overwrites any shipped one,
  #  - build fails if any compiled source or required auxiliary file is
  #    missing from the assembled dir (no silently empty components).
  mkComponent =
    { name          # IDF component name
    , src           # store path of the library source (flake input)
    , srcsList ? [ ]      # files compiled by idf_component_register SRCS
    , includeDirs         # INCLUDE_DIRS, relative to component root
    , requires ? [ ]      # REQUIRES (public component deps)
    , mustExist ? [ ]     # extra files that must be present (headers, .inc)
    }:
    let
      registerArgs = lib.concatStringsSep "\n"
        (lib.optional (srcsList != [ ]) "  SRCS ${quoted srcsList}"
          ++ [ "  INCLUDE_DIRS ${quoted includeDirs}" ]
          ++ lib.optional (requires != [ ]) "  REQUIRES ${toString requires}");
      cmakeLists = pkgs.writeText "${name}-CMakeLists.txt" ''
        # Generated by nix/arduino-libs.nix — IDF 4.4 component for ${name}
        idf_component_register(
        ${registerArgs}
        )
      '';
      checked = srcsList ++ mustExist;
    in
    pkgs.runCommand "idf-component-${name}"
      {
        preferLocalBuild = true;
        allowSubstitutes = false;
      } ''
      mkdir -p "$out"
      cp -r ${src}/. "$out"/
      chmod -R u+w "$out"
      cp ${cmakeLists} "$out"/CMakeLists.txt
      for f in ${toString checked}; do
        if [ ! -e "$out/$f" ]; then
          echo "component ${name}: expected file '$f' missing in assembled dir" >&2
          exit 1
        fi
      done
    '';
in
{
  # IDF component name -> derivation ($out = component dir).
  # Does NOT include the "arduino" core component itself.
  components = {
    # Header-only (v6): everything lives under src/ArduinoJson + src/ArduinoJson.h.
    ArduinoJson = mkComponent {
      name = "ArduinoJson";
      src = srcs.arduinojson;
      srcsList = [ ];
      includeDirs = [ "src" ];
      mustExist = [ "src/ArduinoJson.h" "src/ArduinoJson.hpp" ];
    };

    # Links2004/arduinoWebSockets 2.7.3. On ESP32 with arduino-esp32 >= 1.0.6
    # WebSockets.cpp includes "sha/sha_parallel_engine.h", which IDF 4.4 ships
    # in the mbedtls component's port includes -> REQUIRES mbedtls.
    # CORE_HAS_LIBB64 is never defined on ESP32, so the bundled libb64 is
    # used and must be compiled; libsha1 is inert on ESP32 but compiled for
    # parity with the reference build (unused objects are GC'd).
    WebSockets = mkComponent {
      name = "WebSockets";
      src = srcs.websockets;
      srcsList = [
        "src/SocketIOclient.cpp"
        "src/WebSockets.cpp"
        "src/WebSocketsClient.cpp"
        "src/WebSocketsServer.cpp"
        "src/libb64/cdecode.c"
        "src/libb64/cencode.c"
        "src/libsha1/libsha1.c"
      ];
      includeDirs = [ "src" ];
      requires = [ "arduino" "mbedtls" ];
      mustExist = [ "src/WebSocketsClient.h" "src/libb64/cencode_inc.h" ];
    };

    # Flat layout (sources at repo root). library.properties: no depends,
    # but uses Arduino.h/Wire.h/SPI.h -> arduino.
    Adafruit_BusIO = mkComponent {
      name = "Adafruit_BusIO";
      src = srcs.adafruit-busio;
      srcsList = [
        "Adafruit_BusIO_Register.cpp"
        "Adafruit_GenericDevice.cpp"
        "Adafruit_I2CDevice.cpp"
        "Adafruit_SPIDevice.cpp"
      ];
      includeDirs = [ "." ];
      requires = [ "arduino" ];
      mustExist = [ "Adafruit_I2CDevice.h" "Adafruit_SPIDevice.h" ];
    };

    Adafruit_Sensor = mkComponent {
      name = "Adafruit_Sensor";
      src = srcs.adafruit-sensor;
      srcsList = [ "Adafruit_Sensor.cpp" ];
      includeDirs = [ "." ];
      requires = [ "arduino" ];
      mustExist = [ "Adafruit_Sensor.h" ];
    };

    # library.properties: depends=Adafruit BusIO. glcdfont.c is #include'd by
    # Adafruit_GFX.cpp (not compiled standalone) and must be present.
    Adafruit_GFX = mkComponent {
      name = "Adafruit_GFX";
      src = srcs.adafruit-gfx;
      srcsList = [
        "Adafruit_GFX.cpp"
        "Adafruit_GrayOLED.cpp"
        "Adafruit_SPITFT.cpp"
      ];
      includeDirs = [ "." ];
      requires = [ "arduino" "Adafruit_BusIO" ];
      mustExist = [ "glcdfont.c" "gfxfont.h" "Fonts" ];
    };

    # library.properties: depends=Adafruit GFX Library. BusIO headers reach it
    # transitively via Adafruit_GFX, listed explicitly for robustness.
    Adafruit_SSD1306 = mkComponent {
      name = "Adafruit_SSD1306";
      src = srcs.adafruit-ssd1306;
      srcsList = [ "Adafruit_SSD1306.cpp" ];
      includeDirs = [ "." ];
      requires = [ "arduino" "Adafruit_GFX" "Adafruit_BusIO" ];
      mustExist = [ "Adafruit_SSD1306.h" "splash.h" ];
    };

    # library.properties: depends=Adafruit Unified Sensor, Adafruit BusIO.
    Adafruit_BME280 = mkComponent {
      name = "Adafruit_BME280";
      src = srcs.adafruit-bme280;
      srcsList = [ "Adafruit_BME280.cpp" ];
      includeDirs = [ "." ];
      requires = [ "arduino" "Adafruit_Sensor" "Adafruit_BusIO" ];
      mustExist = [ "Adafruit_BME280.h" ];
    };

    # library.properties: depends=Adafruit Unified Sensor, Adafruit BusIO.
    Adafruit_BMP280 = mkComponent {
      name = "Adafruit_BMP280";
      src = srcs.adafruit-bmp280;
      srcsList = [ "Adafruit_BMP280.cpp" ];
      includeDirs = [ "." ];
      requires = [ "arduino" "Adafruit_Sensor" "Adafruit_BusIO" ];
      mustExist = [ "Adafruit_BMP280.h" ];
    };

    # library.properties: depends=Adafruit Unified Sensor (used by DHT_U).
    DHT = mkComponent {
      name = "DHT";
      src = srcs.dht-sensor;
      srcsList = [ "DHT.cpp" "DHT_U.cpp" ];
      includeDirs = [ "." ];
      requires = [ "arduino" "Adafruit_Sensor" ];
      mustExist = [ "DHT.h" "DHT_U.h" ];
    };

    BH1750 = mkComponent {
      name = "BH1750";
      src = srcs.bh1750;
      srcsList = [ "src/BH1750.cpp" ];
      includeDirs = [ "src" ];
      requires = [ "arduino" ];
      mustExist = [ "src/BH1750.h" ];
    };

    # Plain C, no Arduino dependency. uECC.c #include's the .inc files and
    # types.h; no asm optimizations enabled (library defaults).
    micro_ecc = mkComponent {
      name = "micro_ecc";
      src = srcs.micro-ecc;
      srcsList = [ "uECC.c" ];
      includeDirs = [ "." ];
      mustExist = [
        "uECC.h"
        "uECC_vli.h"
        "types.h"
        "curve-specific.inc"
        "platform-specific.inc"
        "asm_arm.inc"
        "asm_avr.inc"
      ];
    };

    # library.properties: depends=Sensirion Core; header includes
    # SensirionCore.h and Wire.h.
    sps30 = mkComponent {
      name = "sps30";
      src = srcs.sps30;
      srcsList = [ "src/SensirionI2cSps30.cpp" ];
      includeDirs = [ "src" ];
      requires = [ "arduino" "sensirion_core" ];
      mustExist = [ "src/SensirionI2cSps30.h" ];
    };

    sensirion_core = mkComponent {
      name = "sensirion_core";
      src = srcs.sensirion-core;
      srcsList = [
        "src/SensirionCrc.cpp"
        "src/SensirionErrors.cpp"
        "src/SensirionI2CCommunication.cpp"
        "src/SensirionI2CTxFrame.cpp"
        "src/SensirionRxFrame.cpp"
        "src/SensirionShdlcCommunication.cpp"
        "src/SensirionShdlcTxFrame.cpp"
      ];
      includeDirs = [ "src" ];
      requires = [ "arduino" ];
      mustExist = [ "src/SensirionCore.h" ];
    };

    # Serials.h only pulls SoftwareSerial on non-ESP32 targets; on ESP32 it
    # uses HardwareSerial from the arduino core.
    sds011 = mkComponent {
      name = "sds011";
      src = srcs.sds011;
      srcsList = [
        "src/SdsDustSensor.cpp"
        "src/SdsDustSensorResults.cpp"
      ];
      includeDirs = [ "src" ];
      requires = [ "arduino" ];
      mustExist = [ "src/SdsDustSensor.h" "src/Serials.h" ];
    };
  };

  # Always linked: unconditional includes in src/main.cpp, plus the sensor
  # libs kept compiled everywhere for parity with the pre-nix reference
  # build (linker GCs unused objects).
  baseComponents = [
    "ArduinoJson"
    "WebSockets"
    "Adafruit_BusIO"
    "Adafruit_Sensor"
    "Adafruit_GFX"
    "Adafruit_SSD1306"
    "Adafruit_BME280"
    "Adafruit_BMP280"
    "BH1750"
    "micro_ecc"
    "DHT"
  ];

  # Variant flag -> extra component names (not part of the reference build).
  conditional = {
    sps30 = [ "sensirion_core" "sps30" ];
    sds011 = [ "sds011" ];
  };
}
